name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - '3.0'
          - 3.1
          - head
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: imagemagick ghostscript
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: test
        run: bundle exec rake test
        continue-on-error: ${{ matrix.ruby == 'head' }}
